version: "3.9"

services:
  backend:
    build:
      context: ./japan-go-be
      dockerfile: Dockerfile
    container_name: japan-go-be-app
    ports:
      - "2509:2509"
    environment:
      SPRING_PROFILES_ACTIVE: uat
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/japan-go?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ""
      SPRING_DATA_REDIS_DATABASE: 0
      SOURCES_URI: file:///app/sources
    volumes:
      - ./sources:/app/sources
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./japan-go-fe
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:2509/api/v1
    container_name: japan-go-fe-app
    environment:
      API_URL: http://backend:2509/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: japan-go-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: japan-go
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: japan-go-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql_data:
